// <auto-generated />
using System;
using IdeasAPI.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace IdeasAPI.Migrations
{
    [DbContext(typeof(IdeaContext))]
    [Migration("20190327174719_InitialAzure")]
    partial class InitialAzure
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.3-servicing-35854")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("IdeasAPI.Models.Idea", b =>
                {
                    b.Property<int>("IdeaID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("Colour");

                    b.Property<DateTime>("DateCreated");

                    b.Property<string>("FromCountry");

                    b.Property<string>("IdeaText")
                        .HasMaxLength(500);

                    b.Property<bool>("IsConundrum");

                    b.Property<int?>("ParentID");

                    b.Property<int>("Score");

                    b.Property<int>("TreeID");

                    b.HasKey("IdeaID");

                    b.HasIndex("ParentID");

                    b.HasIndex("TreeID");

                    b.ToTable("Ideas");
                });

            modelBuilder.Entity("IdeasAPI.Models.Tree", b =>
                {
                    b.Property<int>("TreeID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Date");

                    b.HasKey("TreeID");

                    b.ToTable("Trees");
                });

            modelBuilder.Entity("IdeasAPI.Models.Idea", b =>
                {
                    b.HasOne("IdeasAPI.Models.Idea", "ParentIdea")
                        .WithMany("ChildrenIdeas")
                        .HasForeignKey("ParentID");

                    b.HasOne("IdeasAPI.Models.Tree", "Tree")
                        .WithMany("Ideas")
                        .HasForeignKey("TreeID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
