// <auto-generated />
using System;
using IdeasAPI.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace IdeasAPI.Migrations
{
    [DbContext(typeof(IdeaContext))]
    partial class IdeaContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.2.2-servicing-10034")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("IdeasAPI.Models.Idea", b =>
                {
                    b.Property<long>("IdeaID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("FromCountry");

                    b.Property<string>("IdeaText");

                    b.Property<DateTime>("TimeCreated");

                    b.HasKey("IdeaID");

                    b.ToTable("Ideas");
                });
#pragma warning restore 612, 618
        }
    }
}
